# Build settings
markdown: kramdown


# Site settings
title: William Brown
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal website/blog! This is just a test of jekyll
  for now, though I will expand it to cover cool coding things!

author:
  name:       'William A O Brown'
  url:         "https://willb611.github.io/"


paginate: 1
github_username:  Willb611


# Pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

sass:
  sass_dir: _scss
  style: :compressed
