# Site settings
title: Home
email: william.brown-4@student.manchester.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal website/blog! This is just a test of jekyll
  for now, though I will expand it to cover cool coding things!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: will61153
github_username:  Willb611

# Build settings
markdown: kramdown
